
const vocabChuong2 = {
    "học sinh cấp 1": "しょうがくせい",
    "học sinh cấp 2": "ちゅうがくせい",
    "học sinh cấp 3": "こうこうせい",
    "thầy cô đại học": "だいがくのせんせい",
    "nhân viên FPT": "FPTのしゃいん",
    "thầy cô của tôi": "わたしのせんせい",
    "thầy cô và học sinh": "せんせいとがくせい",
    "Cái này (vật gần người nói)": "これ",
    "Cái đó (vật gần người nghe)": "それ",
    "Cái kia (vật xa cả hai)": "あれ",
    "Cặp": "かばん",
    "Sách": "ほん",
    "Từ điển": "じしょ",
    "Sổ tay": "てちょう",
    "Hộp bút": "ふでばこ",
    "Bút chì chuốt": "えんぴつ",
    "Cục gôm, tẩy": "けしごむ",
    "Tờ báo": "しんぶん",
    "Tạp chí": "ざっし",
    "Cái bàn": "つくえ",
    "Cái ghế": "いす",
    "Quạt máy": "せんぷうき",
    "Ô, dù": "かさ",
    "Nón": "ぼうし",
    "Mắt kính": "めがね",
    "Đồng hồ": "とけい",
    "Ví tiền": "さいふ",
    "Giày": "くつ",
    "Điện thoại": "でんわ",
    "Chìa khóa": "かぎ",
    "Xe đạp": "じてんしゃ",
    "Xe hơi": "じどうしゃ / くるま",
    "Xe máy": "ばいく",
    "Bánh kẹo": "おかし",
    "Là cái gì?": "なんですか？",
    "~ của ai?": "だれの ～？",
    "~ của nước nào?": "どこの ～？",
    "~ gì?": "なんの ～？",
    "Tiếng ~": "～ご",
    "Tiếng Nhật": "にほんご",
    "Tiếng Trung Quốc": "ちゅうごくご",
    "Tiếng Anh": "えいご",
    "Tiếng gì?": "なにご？",
    "Cái nào?": "どれですか？",
    "Là ~ nào?": "どの ～ですか？",
    "~ này": "この ～",
    "~ đó": "その ～",
    "~ kia": "あの ～",
    "Trường học": "がっこう",
    "Công ty": "かいしゃ",
    "Phòng": "へや",
    "Vật, đồ vật, hàng hóa": "もの",
    "Bảng đen": "こくばん",
    "Điện, đèn": "でんき",
    "Máy chụp hình": "カメラ",
    "Vở, quyển vở": "ノート",
    "Máy lạnh": "クーラー",
    "Đàn ông": "おとこ",
    "Phụ nữ": "おんな",
    "Vâng, đúng vậy": "はい、そうです",
    "Không, không phải vậy": "いいえ、ちがいます",
    "Tivi": "てれび",
    "Bản đồ": "ちず",
    "Cái bút (pen)": "ぺん",
    "Bút bi (borupen)": "ぼーるぺん"
};