// File: chuong4.js
const vocabChuong4 = {
    // Thời gian và các buổi
    "Bây giờ": "いま",
    "Vừa đúng": "ちょうど",
    "Trước (kém) ~": "～まえ",
    "Buổi sáng (trước 12 giờ trưa)": "ごぜん",
    "Buổi chiều (sau 12 giờ trưa)": "ごご",
    "Sáng": "あさ",
    "Trưa": "ひる",
    "Chiều": "ゆうがた",
    "Tối": "よる・ばん",
    
    // Thứ trong tuần
    "Thứ mấy?": "なんようび",
    "Chủ nhật": "にちようび",
    "Thứ hai": "げつようび",
    "Thứ ba": "かようび",
    "Thứ tư": "すいようび",
    "Thứ năm": "もくようび",
    "Thứ sáu": "きんようび",
    "Thứ bảy": "どようび",
    
    // Thời gian tương đối (Hôm nay, mai...)
    "Hôm nay": "きょう",
    "Ngày mai": "あした",
    "Ngày mốt": "あさって",
    "Hôm qua": "きのう",
    "Hôm kia": "おととい",
    
    // Ngày trong tháng
    "Ngày mấy?": "なんにち",
    "Ngày 1": "ついたち",
    "Ngày 2": "ふつか",
    "Ngày 3": "みっか",
    "Ngày 4": "よっか",
    "Ngày 5": "いつか",
    "Ngày 6": "むいか",
    "Ngày 7": "なのか",
    "Ngày 8": "ようか",
    "Ngày 9": "ここのか",
    "Ngày 10": "とおか",
    "Ngày 11": "じゅういちにち",
    "Ngày 12": "じゅうににち",
    "Ngày 13": "じゅうさんにち",
    "Ngày 14": "じゅうよっか",
    "Ngày 15": "じゅうごにち",
    "Ngày 16": "じゅうろくにち",
    "Ngày 17": "じゅうしちにち",
    "Ngày 18": "じゅうはちにち",
    "Ngày 19": "じゅうくにち",
    "Ngày 20": "はつか",
    "Ngày 21": "にじゅういちにち",
    "Ngày 22": "にじゅうににち",
    "Ngày 23": "にじゅうさんにち",
    "Ngày 24": "にじゅうよっか",
    "Ngày 25": "にじゅうごにち",
    "Ngày 26": "にじゅうろくにち",
    "Ngày 27": "にじゅうしちにち",
    "Ngày 28": "にじゅうはちにち",
    "Ngày 29": "にじゅうくにち",
    "Ngày 30": "さんじゅうにち",
    "Ngày 31": "さんじゅういちにち",

    // Tháng
    "Tháng mấy?": "なんがつ",
    "Tháng 1": "いちがつ",
    "Tháng 2": "にがつ",
    "Tháng 3": "さんがつ",
    "Tháng 4": "しがつ",
    "Tháng 5": "ごがつ",
    "Tháng 6": "ろくがつ",
    "Tháng 7": "しちがつ",
    "Tháng 8": "はちがつ",
    "Tháng 9": "くがつ",
    "Tháng 10": "じゅうがつ",
    "Tháng 11": "じゅういちがつ",
    "Tháng 12": "じゅうにがつ",
    "Tháng này": "こんげつ",
    "Tháng tới": "らいげつ",
    "Tháng tới nữa": "さらいげつ",
    "Tháng trước": "せんげつ",
    "Tháng trước nữa": "せんせんげつ",
    "Cuối tháng": "げつまつ",
    "Ngày sinh nhật": "たんじょうび",
    "Ngày sinh nhật (lịch sự)": "おたんじょうび",
    "Khi nào, lúc nào?": "いつ",

    // Năm
    "Năm mấy?": "なんねん",
    "Năm (2025)": "2025ねん",
    "Năm nay": "ことし",
    "Năm tới": "らいねん",
    "Năm tới nữa": "さらいねん",
    "Năm ngoái": "きょねん",
    "Năm kia": "おととし",
    "Cuối năm": "ねんまつ",
    "Ngày tháng năm sinh": "せいねんがっぴ",

    // Hoạt động và thời gian nghỉ
    "Từ ~": "～から",
    "Đến ~": "～まで",
    "Giờ học, tiết học": "じゅぎょう",
    "Việc học": "べんきょう",
    "Kỳ thi, bài thi": "しけん",
    "Ngày nghỉ, kỳ nghỉ, giờ nghỉ": "やすみ",
    "Nghỉ trưa": "ひるやすみ",
    "Nghỉ xuân": "はるやすみ",
    "Nghỉ hè": "なつやすみ",
    "Nghỉ đông": "ふゆやすみ",
    "Giờ ra chơi, giờ nghỉ giữa tiết học": "やすみじかん",
    "Thời gian nghỉ giải lao": "きゅうけいじかん",
    "Cuộc họp, hội nghị": "かいぎ",
    "Công tác, việc đi công tác": "しゅっちょう",
    "Du lịch, chuyến du lịch": "りょこう",
    "Du lịch nhân viên (tập thể công ty)": "しゃいんりょこう",
    "Bài kiểm tra": "テスト",
    
    // --- PHẦN MỞ RỘNG MỚI (Mùa, Thời tiết, Tuần, Định kỳ) ---
    "Mùa xuân": "はる",
    "Mùa hè": "なつ",
    "Mùa thu": "あき",
    "Mùa đông": "ふゆ",
    "Mưa": "あめ",
    "Trời trong xanh, nắng đẹp": "はれ",
    "Trời âm u": "くもり",
    "Tuần này": "こんしゅう",
    "Tuần tới": "らいしゅう",
    "Tuần tới nữa": "さらいしゅう",
    "Tuần trước": "せんしゅう",
    "Tuần trước nữa": "せんせんしゅう",
    "Cuối tuần": "しゅうまつ",
    "Mỗi sáng": "まいあさ",
    "Mỗi tối": "まいばん",
    "Mỗi ngày": "まいにち",
    "Mỗi tuần": "まいしゅう",
    "Mỗi tháng": "まいつき",
    "Mỗi năm": "まいとし"
};