const vocabChuong11 = {
    "Hỏi (giáo viên)": "きく",
    "Cho mượn, cho thuê": "かす",
    "Nộp, gửi": "だす",
    "Trả lại": "かえす",
    "Gửi": "おくる",
    "Cho xem": "みせる",
    "Sử dụng / Dùng": "つかう",
    "Gọi điện thoại": "でんわをかける",
    "Nghe (từ bạn bè)": "きく",
    "Học": "ならう",
    "Mượn, vay, thuê": "かりる",
    "Vào (phòng học)": " はいる", // hoặc はいる
    "Lên (xe), cưỡi (ngựa)": "のる",
    "Leo (núi)": "のぼる",
    "Đến (sân bay)": "つく",
    "Rời khỏi (nhà)": "でる",
    "Xuống (xe)": "おりる",
    "Tốt nghiệp (đại học)": "そつぎょうする",
    "Xuất phát, rời (sân bay)": "しゅっぱつする",
    "Từ, ngôn ngữ": "ことば",
    "Ý nghĩa": "いみ",
    "Tiền": "おかね", // hoặc おかね
    "Trưởng phòng": "ぶちょう",
    "Trưởng ban": "かちょう",
    "Câu chuyện": "はなし",
    "Bồn tắm": "おふろ",
    "Thư điện tử": "メール",

    // --- PHẦN MỞ RỘNG ---
    "Bay (trên bầu trời)": "とぶ",
    "Chạy (trên đường)": "はしる",
    "Đi (qua đường)": "とおる",
    "Băng (qua cầu)": "わたる",
    "Đi bộ (trong công viên)": "あるく",
    "Tản bộ (trong vườn)": "さんぽする",
    "Du lịch (Tokyo)": "りょこうする",
    "Đứng (ở lối vào)": "たつ",
    "Ngồi (ở đằng kia)": "すわる",
    "Trọ lại, ngủ lại (khách sạn)": "とまる",
    "Dừng, đậu (mỗi ga)": "とまる",
    "Đặt, để xe đạp (ở ...)": "おく",
    "Dán tem (vào phong bì)": "はる",
    "Bỏ bia (vào tủ lạnh)": "いれる",
    "Treo lịch (lên tường)": "かける",
    "Trả lời (cho ...)": "こたえる",
    "Đặt câu hỏi": "しつもんする",
    "Chia tay (với ...)": "わかれる",
    "Thi đấu": "しあいをする",
    "Chiến đấu": "せんそうをする",
    "Kết hôn": "けっこんする"
};