// File: chuong10.js
const vocabChuong10 = {
    // --- PHẦN CHÍNH ---
    "Tốn (thời gian, tiền)": "かかる",
    "(giờ học) Bắt đầu": "はじまる",
    "(giờ học) Kết thúc": "おわる",
    "Đánh (răng)": "(はを)みがく",
    "Kiểm tra sức khỏe": "うける",
    "Mỗi sáng": "まいあさ",
    "Mỗi tối": "まいばん",
    "Mỗi ngày": "まいにち",
    "Mỗi tuần": "まいしゅう",
    "Mỗi tháng": "まいつき",
    "Mỗi năm": "まいとし",
    "Tết": "おしょうがつ",
    "Nghỉ xuân": "はるやすみ",
    "Nghỉ hè": "なつやすみ",
    "Nghỉ đông": "ふゆやすみ",
    "Tàu cánh ngầm cao tốc": "こうそくせん",
    "~ Lần": "~かい",
    "Bao nhiêu lần ?": "なんかい",
    "Bố mẹ": "りょうしん",
    "Bố": "ちち",
    "Mẹ": "はは",
    "Anh chị em": "きょうだい",
    "Anh trai": "あに",
    "Em trai": "おとうと",
    "Chị gái": "あね",
    "Em gái": "いもうと",
    "Bạn thân": "しんゆう",
    "Anh ấy / Bạn trai": "かれ",
    "Chị ấy / Bạn gái": "かのじょ",

    // --- PHẦN MỞ RỘNG & THỜI LƯỢNG ---
    "Mệt": "つかれる",
    "Lễ hội": "おまつり",
    "Xe Grab": "グラブ",
    "Việc làm thêm": "アルバイト",
    "Cầu lông": "バドミントン",
    "Phòng tập Gym": "ジム",
    "Một giờ": "いちじかん",
    "Hai giờ": "にじかん",
    "Ba giờ": "さんじかん",
    "Bốn giờ": "よじかん",
    "Năm giờ": "ごじかん",
    "Sáu giờ": "ろくじかん",
    "Bảy giờ": "ななじかん",
    "Tám giờ": "はちじかん",
    "Chín giờ": "くじかん",
    "Mười giờ": "じゅうじかん",
    "Mấy giờ (thời lượng)": "なんじかん",
    "Một ngày (thời lượng)": "いちにち(かん) 時間",
    "Hai ngày": "ふつか(かん)",
    "Ba ngày": "みっか(かん)",
    "Bốn ngày": "よっか(かん)",
    "Năm ngày": "いつか(かん)",
    "Sáu ngày": "むいか(かん)",
    "Bảy ngày": "なのか(かん)",
    "Tám ngày": "ようか(かん)",
    "Chín ngày": "ここのか(かん)",
    "Mười ngày": "とおか(かん)",
    "Mấy ngày": "なんにち(かん)",
    "Một tuần": "いっしゅうかん",
    "Hai tuần": "にしゅうかん",
    "Ba tuần": "さんしゅうかん",
    "Bốn tuần": "よんしゅうかん",
    "Năm tuần": "ごしゅうかん",
    "Sáu tuần": "ろくしゅうかん",
    "Bảy tuần": "ななしゅうかん",
    "Tám tuần": "はっしゅうかん",
    "Chín tuần": "きゅうしゅうかん",
    "Mười tuần": "じゅっしゅうかん",
    "Mấy tuần": "なんしゅうかん",
    "Một tháng": "いっかげつ",
    "Hai tháng": "にかげつ",
    "Ba tháng": "さんかげつ",
    "Bốn tháng": "よんかげつ",
    "Năm tháng": "ごかげつ",
    "Sáu tháng (nửa năm)": "ろっかげつ",
    "Bảy tháng": "ななかげつ",
    "Tám tháng": "はちかげつ",
    "Chín tháng": "きゅうかげつ",
    "Mười tháng": "じゅっかげつ",
    "Mấy tháng": "なんかげつ",
    "Khoảng chừng (thời gian/số lượng)": "どのぐらい",
    "Tốn / Mất (thời gian, tiền bạc)": "かかる",
    "Chỉ (đi với khẳng định)": "だけ",
    "Mấy lần / Bao nhiêu lần?": "なんかい (何回)",
};