// File: chuong7.js
const vocabChuong7 = {
    // --- V1: Động từ nhóm 1 ---
    "Học (tiếng Nhật)": "にほんごを ならう",
    "Rửa (mặt)": "かおを あらう",
    "Mua (trái cây)": "くだものを かう",
    "Viết (thư)": "てがみを かく",
    "Nghe (nhạc)": "おんがくを きく",
    "Nói chuyện (tiếng Nhật)": "にほんごで はなす",
    "Đọc (báo)": "しんぶんを よむ",
    "Uống (trà)": "おちゃを のむ",
    "Nấu (món ăn)": "りょうりを つくる",
    "Đi (công viên)": "こうえんに いく",
    "Về (nhà)": "うちにかえる",
    "Quay lại (phòng)": "へやに もどる",
    "Vào (phòng, quán nước...)": "へやに はいる",

    // --- V2: Động từ nhóm 2 ---
    "Chỉ, dạy (tiếng Nhật)": "にほんごを おしえる",
    "Ăn (cơm)": "ごはんを たべる",
    "Xem (tivi)": "テレビを みる",

    // --- V3: Động từ nhóm 3 ---
    "Làm (bài tập)": "しゅくだいを する",
    "Làm (việc)": "しごとを する",
    "Làm, tổ chức (tiệc)": "パーティーを する",
    "Chơi (thể thao)": "スポーツを する",
    "Đến (trường)": "がっこうに くる",

    // --- Danh từ cơ bản ---
    "Mặt": "かお",
    "Lá thư": "てがみ",
    "Nhật ký": "にっき",
    "Âm nhạc": "おんがく",
    "Phim": "えいが",
    "Nước": "みず",
    "Trà": "おちゃ",
    "Sữa bò": "ぎゅうにゅう",
    "Cơm": "ごはん",
    "Cơm sáng": "あさごはん",
    "Cơm trưa": "ひるごはん",
    "Cơm tối": "ばんごはん",
    "Trứng": "たまご",
    "Trái cây": "くだもの",
    "Thịt": "にく", // Lấy từ list cũ bù vào nếu cần theo mạch học
    
    // --- Phương tiện & Gia đình (Trang 85) ---
    "Máy bay": "ひこうき",
    "Tàu cao tốc": "しんかんせん",
    "Thuyền": "ふね",
    "Tàu cánh ngầm cao tốc": "こうそくせん",
    "Đôi đũa": "はし",
    "Gia đình": "かぞく",
    "Bố mẹ": "りょうしん",
    "Bố": "ちち",
    "Bố bạn": "おとうさん",
    "Mẹ": "はは",
    "Mẹ bạn": "おかあさん",
    "Anh chị em": "きょうだい",
    "Anh trai": "あに",
    "Anh trai bạn": "おにいさん",
    "Em trai": "おとうと",
    "Em trai bạn": "おとうとさん",
    "Chị gái": "あね",
    "Chị gái bạn": "おねえさん",
    "Em gái": "いもうと",
    "Em gái bạn": "いもうとさん",
    "Bạn thân": "しんゆう",
    "Bạn bè": "ともだち",
    "Người yêu": "こいびと",
    "Người cùng công ty": "かいしゃのひと",
    "Một mình": "ひとりで",
    "Cuối tuần": "しゅうまつ",

    // --- Từ ngoại lai (Katakana) ---
    "Tivi": "テレビ",
    "Phim hoạt hình": "アニメ",
    "Bài báo cáo": "レポート",
    "Trà sữa": "ミルクティー",
    "Nước ép trái cây": "ジュース",
    "Cà phê": "コーヒー",
    "Bia": "ビール",
    "Bánh mì": "パン",
    "Bóng đá": "サッカー",
    "Quần vợt, tennis": "テニス",
    "Siêu thị": "スーパー",
    "Cửa hàng tiện lợi": "コンビニ",
    "Cái muỗng": "スプーン",
    "Cái nĩa": "フォーク",
    "Con dao": "ナイフ",
    "Youtube": "ユーチューブ",

    // --- Phần mở rộng: Danh từ đi với する (Nhóm 3) ---
    "Học": "べんきょう（を）する",
    "Luyện tập": "れんしゅう（を）する",
    "Trao đổi, tham khảo ý kiến": "そうだん（を）する",
    "Du học": "りゅうがく（を）する",
    "Nấu món ăn (động từ)": "りょうり（を）する",
    "Dùng bữa": "しょくじ（を）する",
    "Mua sắm": "かいもの（を）する",
    "Đi dạo": "さんぽ（を）する",
    "Quét dọn": "そうじ（を）する",
    "Giặt giũ": "せんたく（を）する",
    "Tập thể dục": "うんどう（を）する",
    "Lái xe": "うんてん（を）する",
    "Du lịch": "りょこう（を）する",
    "Đi công tác": "しゅっちょう（を）する",
    "Kết hôn": "けっこん（を）する",
    "Hát karaoke": "カラオケ（を）する",
    "Chạy bộ": "ジョギング（を）する",
    "Đi chơi dã ngoại": "ハイキング（を）する"
};