// File: chuong1.js
const vocabChuong1 = {
    "Chào buổi sáng": "おはよう ございます",
    "Chào buổi trưa": "こんにちは",
    "Chào buổi tối": "こんばんは",
    "Tạm biệt bạn nhé": "さようなら",
    "Chúc bạn ngủ ngon": "おやすみ なさい",
    "Xin chúc mừng bạn": "おめでとう ございます",
    "Xin cảm ơn bạn": "ありがとう ございます",
    "Bạn khỏe không?": "おげんき ですか",
    "Vâng, tôi khỏe": "はい、げんき です",
    "Hân hạnh được gặp bạn": "はじめまして",
    "Rất mong được bạn giúp đỡ": "よろしく おねがいします",
    "Tôi": "わたし",
    "Chúng tôi": "わたしたち",
    "Bạn, anh, chị (ngôi thứ 2)": "あなた",
    "Người": "ひと",
    "Người này": "この ひと",
    "Người kia": "あの ひと",
    "Vị": "かた",
    "Vị này": "この かた",
    "Vị kia": "あの かた",
    "Bạn~, anh~, chị~, ông~, bà~": "～さん",
    "Thầy, Cô": "せんせい",
    "Học sinh, học viên": "がくせい",
    "Sinh viên": "だいがくせい",
    "Giáo viên": "きょうし",
    "Nhân viên cửa hàng": "てんいん",
    "Nhân viên công ty": "かいしゃいん",
    "Nhân viên ngân hàng": "ぎんこういん",
    "Bác sĩ": "いしゃ",
    "Nội trợ": "しゅふ",
    "Ca sĩ": "かしゅ",
    "Tài xế": "うんてんしゅ",
    "Công việc": "しごと",
    "(Anh / Chị) làm công việc gì?": "おしごとは？",
    "Vâng": "はい",
    "Không": "いいえ",
    "Ai?": "だれ？",
    "Ai, vị nào?": "どなた？",
    "Tên": "なまえ",
    "(Anh / Chị) tên gì?": "おなまえは？",
    "Việt Nam": "べとなむ",
    "Nhật Bản": "にほん",
    "Hàn Quốc": "かんこく",
    "Trung Quốc": "ちゅうごく",
    "Đài Loan": "たいわん",
    "Người ~": "～じん",
    "Người Việt Nam": "べとなむじん",
    "Người Nhật Bản": "にほんじん",
    "Quốc tịch": "こくせき",
    "(Anh / Chị) quốc tịch gì?": "ごこくせきは？",
    "Hiệu trưởng": "こうちょう",
    "Giám đốc": "しゃちょう",
    "Cửa hàng trưởng": "てんちょう",
    "Cán bộ nhà nước": "こうむいん",
    "Cảnh sát": "けいさつかん",
    "Đầu bếp": "ちょうりし",
    "Luật sư": "べんごし",
    "Y tá": "かんごし",
    "Điều dưỡng": "かいごし",
    "Kỹ sư": "えんじにあ",
    "Thái Lan": "たい",
    "Ấn Độ": "いんど",
    "Anh": "いぎりす",
    "Pháp": "ふらんす",
    "Mỹ": "あめりか",
    "Đức": "どいつ",
    "Ý": "いたりあ",
    "Một lần nữa": "もういちど",
    "Xin vui lòng lặp lại lần nữa": "もういちど おねがいします",
    "Hãy đứng lên": "たってください",
    "Hãy ngồi xuống": "すわってください",
    "Hãy nói": "いってください",
    "Hãy viết": "かいてください",
    "Hãy nghe": "きいてください",
    "Hãy đọc": "よんでください",
    "Hãy nhìn": "みてください",
    "Hãy nhớ": "おぼえてください",
    "Chúng ta bắt đầu nào": "はじめましょう",
    "Chúng ta nghỉ giải lao nào": "やすみましょう",
    "Chúng ta kết thúc nào": "おわりましょう",
    "Xin lỗi (khi làm phiền/gọi ai đó)": "すみません",
    "Xin mời": "どうぞ"
};